name: "Deploy server"
on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      SERVER_HOST: mc.nasirk.ca
      PROFILE: server
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: cachix/cachix-action@v14
      with:
        name: nasirserver
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        
    - name: Add deploy key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/server
        chmod 600 ~/.ssh/server
        ssh-keyscan -H "$SERVER_HOST" >> ~/.ssh/known_hosts

    - name: Pre-build to ensure everything is cached
      run: |
        nix build .#nixosConfigurations.generic-nixos-facter.config.system.build.toplevel

    - name: Deploy (uses cached outputs)
      run: |
        nix run github:serokell/deploy-rs -- .#server
        
